### ISSUE TITLE
Implement writing to and reading from config file

### ISSUE THREAD

**Issue by colececil** [colececil/familiar.sh#5]
Write code that implements writing to and reading from the Familiar.sh config file. These functions will be called from the various Familiar.sh commands.

As part of this task, the YAML structure of the config file should be defined. It needs to support all the functionality of Familiar.sh: package management, configuration files, and scripts.

**Comment by colececil** [comment]
Here is an example of a Familiar.sh config file, to show its structure:

```yaml
version: 1
files:
  - sourcePath: ./config-files/.bashrc
    destinationPath: $HOME/.bashrc
  - sourcePath: ./config-files/windows-terminal-settings.json
    operatingSystems:
      - name: windows
        destinationPath: $LOCALAPPDATA/.bashrc
scripts:
  - sourcePath: ./scripts/global-script
  - sourcePath: ./scripts/windows-script.ps1
    operatingSystems:
      - name: windows
packageManagers:
  - name: scoop
    packages:
    - name: git
      version: 2.28.1.windows.1
    - name: 7zip
      version: '22.01'
    - name: neovim
      version: '0.8.0'
  - name: apt
    packages:
    - name: git
      version: 1:2.25.1-1ubuntu3.6
    - name: neovim
      version: '0.4.3-3'
```
